#server.port=8082
#
#spring.application.name=api-server
#
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
server:
  port: 8765


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: Microservice1Note
          uri: http://localhost:8081/
          predicates:
            - Path=/serviceA/**
        - id: Microservice2Task
          uri: http://localhost:8082/
          predicates:
            - Path=/serviceB/**